[general]
modules    = ["crawler", "analyzer"]
version    = "0.7.0 <beta>"
copyright  = "2019 Maximilian Pensel"
master_log = "master.log"

[modloader]
mod_dir = "modules"

[workspace]
default  = "default_workspace"
log_path = "logs"